name: Push Workflow
on:
  # When after commit pushed to branches not master nad release/next
  push:
    branches-ignore:
      - 'master'
      - 'release/next'
env:
  CI: true
jobs:
  init:
    name: 'Install, Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: make clean
      - run: make install
      - run: make build
      - name : Read Version
        run : echo "##[set-output name=VERSION;]$(node -e require('./package.json').version)"
        id : lib_version
  callE2E:
    name : 'Dispatch action on E2E'
    runs-on : ubuntu-latest
    steps:
      - uses : actions/github-script@v6
        with :
          github-token : ${{ secrets.PAT_TOKEN }}
          script : |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'frontegg',
              repo: 'e2e-system-tests',
              workflow_id: 'react.yml',
              ref: 'master'
            })
