name: Push Workflow
on:
  # When after commit pushed to branches not master nad release/next
  push:
    branches-ignore:
      - 'master'
      - 'release/next'
env:
  CI: true
#permissions :
#  actions: write
jobs:
  init:
    name: 'Install, Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: make clean
      - run: make install
      - run: make build
      - name: Read Version
        run: echo "##[set-output name=VERSION;]$(node -e require\('./package.json'\).version)"
        id: lib_version
  update-e2e-wrapper:
    name: 'Build E2E Test Wrapper action'
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout E2E
        uses: actions/checkout@v3
        with:
          repository: frontegg/e2e-system-tests
          path: e2e
      - name: Run E2E tests
        uses: ./e2e/.github/workflows/react
        with:
          lib_version: $${{ steps.lib_version.outputs.VERSION }}
