name: Push Workflow
on:
  # When after commit pushed to branches not master nad release/next
  push:
    branches-ignore:
      - 'master'
      - 'release/next'
env:
  CI: true
jobs:
  init:
    name : Notify Slack on alpha version deployment
    uses : rtCamp/action-slack-notify@v2
    env :
      SLACK_CHANNEL : frontegg-alpha-versions
      SLACK_COLOR : ${{ job.status }}
      SLACK_ICON : https://avatars.githubusercontent.com/u/67857107?s=40&v=4
      SLACK_MESSAGE : 'test'
      SLACK_TITLE : 'test'
      SLACK_USERNAME : ${{ github.actor }}
      SLACK_WEBHOOK : ${{ secrets.SLACK_PRODUCTION_TOKEN }}
      MSG_MINIMAL : Commit,actions url
